name: Healing With Animals
favicon: null
layout_spectrum: 0.28090065787546337
typography_spectrum: 0.7100074859336019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4983310292009264
  lightness: 0.9325856880750507
  saturation: 0.3996358059812337
  rhythmicContrast: 0.5437426648568362
purpose: []
